# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gneiss contributors

# 类型/宏登记和当前公共头一致；生命周期的语义审查仍需对应 Reference 与测试。
file(READ "${GNEISS_SOURCE_DIR}/docs/records/artifacts/0.45-type-inventory.json" type_inventory)
string(JSON header_count LENGTH "${type_inventory}" headers)
math(EXPR header_last "${header_count} - 1")
set(recorded_types)
set(recorded_constants)
set(recorded_headers)
foreach(header_index RANGE 0 ${header_last})
  string(JSON header GET "${type_inventory}" headers ${header_index} header)
  if(header IN_LIST recorded_headers OR NOT EXISTS "${GNEISS_SOURCE_DIR}/${header}")
    message(FATAL_ERROR "类型清单头文件重复或不存在：${header}")
  endif()
  list(APPEND recorded_headers "${header}")
  string(JSON type_count LENGTH "${type_inventory}" headers ${header_index} types)
  if(type_count GREATER 0)
    math(EXPR type_last "${type_count} - 1")
    foreach(type_index RANGE 0 ${type_last})
      string(JSON symbol GET "${type_inventory}" headers ${header_index} types ${type_index} symbol)
      string(JSON mapping GET "${type_inventory}" headers ${header_index} types ${type_index} cpp_mapping)
      string(JSON kind GET "${type_inventory}" headers ${header_index} types ${type_index} kind)
      set(entry "${header}:${symbol}")
      if(entry IN_LIST recorded_types OR mapping STREQUAL "" OR
         NOT kind MATCHES "^(owner|borrowed_id|struct|union|scalar|callback)$")
        message(FATAL_ERROR "类型映射重复或不完整：${entry}")
      endif()
      list(APPEND recorded_types "${entry}")
    endforeach()
  endif()
  string(JSON constant_count LENGTH "${type_inventory}" headers ${header_index} constants)
  if(constant_count GREATER 0)
    math(EXPR constant_last "${constant_count} - 1")
    foreach(constant_index RANGE 0 ${constant_last})
      string(JSON symbol GET "${type_inventory}" headers ${header_index} constants ${constant_index})
      set(entry "${header}:${symbol}")
      if(entry IN_LIST recorded_constants)
        message(FATAL_ERROR "宏清单重复：${entry}")
      endif()
      list(APPEND recorded_constants "${entry}")
    endforeach()
  endif()
endforeach()

set(actual_types)
set(actual_constants)
file(GLOB_RECURSE public_headers RELATIVE "${GNEISS_SOURCE_DIR}"
  "${GNEISS_SOURCE_DIR}/include/gneiss/*.h" "${GNEISS_SOURCE_DIR}/include/gneiss/*.h.in")
foreach(header IN LISTS public_headers)
  file(READ "${GNEISS_SOURCE_DIR}/${header}" content)
  # 单独处理具名结构/联合、标量 typedef 与回调；不把结构字段当成公共类型。
  string(REGEX MATCHALL "typedef[ \t\r\n]+(struct|union)[ \t\r\n]+gneiss_[a-zA-Z0-9_]+" values "${content}")
  foreach(value IN LISTS values)
    string(REGEX MATCH "gneiss_[a-zA-Z0-9_]+$" symbol "${value}")
    list(APPEND actual_types "${header}:${symbol}")
  endforeach()
  string(REGEX MATCHALL "typedef[ \t\r\n]+[a-zA-Z0-9_]+[ \t\r\n]+gneiss_[a-zA-Z0-9_]+[ \t\r\n]*;" values "${content}")
  foreach(value IN LISTS values)
    if(value STREQUAL "")
      continue()
    endif()
    # gneiss_rid 等基类型可能先出现，因此取 typedef 声明的最后一个名字。
    string(REGEX MATCH "gneiss_[a-zA-Z0-9_]+[ \t\r\n]*$" symbol "${value}")
    string(STRIP "${symbol}" symbol)
    list(APPEND actual_types "${header}:${symbol}")
  endforeach()
  string(REGEX MATCHALL "\\(\\*[ \t\r\n]*gneiss_[a-zA-Z0-9_]+\\)" values "${content}")
  foreach(value IN LISTS values)
    string(REGEX MATCH "gneiss_[a-zA-Z0-9_]+" symbol "${value}")
    list(APPEND actual_types "${header}:${symbol}")
  endforeach()
  string(REGEX MATCHALL "#define[ \t]+GNEISS_[A-Z0-9_]+" values "${content}")
  foreach(value IN LISTS values)
    string(REGEX MATCH "GNEISS_[A-Z0-9_]+$" symbol "${value}")
    if(NOT symbol MATCHES "_H_$")
      list(APPEND actual_constants "${header}:${symbol}")
    endif()
  endforeach()
endforeach()
# 条件编译可多次定义同一导出宏，清单只登记一个公共名字。
list(REMOVE_DUPLICATES actual_constants)
list(SORT actual_types)
list(SORT actual_constants)
list(SORT recorded_types)
list(SORT recorded_constants)
if(NOT "${actual_types}" STREQUAL "${recorded_types}")
  message(FATAL_ERROR "公共 C 类型与 C++ 映射清单不一致")
endif()
if(NOT "${actual_constants}" STREQUAL "${recorded_constants}")
  message(FATAL_ERROR "公共 C 宏与清单不一致")
endif()
