# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gneiss contributors

cmake_minimum_required(VERSION 3.23)
file(READ "${GNEISS_SOURCE_DIR}/docs/records/artifacts/0.45-api-inventory.json" inventory)
string(JSON count LENGTH "${inventory}" functions)
math(EXPR last "${count} - 1")
set(symbols)
foreach(index RANGE 0 ${last})
  string(JSON symbol GET "${inventory}" functions ${index} symbol)
  if(symbol IN_LIST symbols)
    message(FATAL_ERROR "重复 API 清单符号：${symbol}")
  endif()
  list(APPEND symbols "${symbol}")
  string(JSON review GET "${inventory}" functions ${index} review)
  if(NOT review STREQUAL "reviewed")
    message(FATAL_ERROR "公共函数尚未完成 C++ 语义审查：${symbol}")
  endif()
  foreach(field IN ITEMS cpp_entry ownership)
    string(JSON value GET "${inventory}" functions ${index} ${field})
    if(value STREQUAL "" OR value STREQUAL "pending")
      message(FATAL_ERROR "公共函数缺少 ${field} 映射：${symbol}")
    endif()
  endforeach()
  string(JSON test_count LENGTH "${inventory}" functions ${index} tests)
  string(JSON wrapper_count LENGTH "${inventory}" functions ${index} cpp_candidate_files)
  if(test_count LESS 1 OR wrapper_count LESS 1)
    message(FATAL_ERROR "公共函数缺少包装或测试证据：${symbol}")
  endif()
  math(EXPR wrapper_last "${wrapper_count} - 1")
  foreach(wrapper_index RANGE 0 ${wrapper_last})
    string(JSON wrapper GET "${inventory}" functions ${index} cpp_candidate_files ${wrapper_index})
    if(NOT EXISTS "${GNEISS_SOURCE_DIR}/${wrapper}")
      message(FATAL_ERROR "公共函数的 C++ 包装文件不存在：${symbol} -> ${wrapper}")
    endif()
  endforeach()
endforeach()
file(STRINGS "${GNEISS_SOURCE_DIR}/abi/api-stability.txt" declarations)
set(expected)
foreach(line IN LISTS declarations)
  if(line MATCHES "^(gneiss_[a-zA-Z0-9_]+) ")
    list(APPEND expected "${CMAKE_MATCH_1}")
  endif()
endforeach()
list(SORT expected)
list(SORT symbols)
if(NOT "${symbols}" STREQUAL "${expected}")
  message(FATAL_ERROR "公共 C API 与 C++ 审计清单不一致；需更新包装及测试映射")
endif()
# 已审查的函数不允许退回 pending 或丢失包装/测试映射；文本检查仍不能代替人工语义审查。

# 已迁移的全部公共 C 定义必须集中于 engine/api，并与声明清单逐项一致。
file(GLOB adapters "${GNEISS_SOURCE_DIR}/src/engine/api/*.cpp")
set(definitions)
foreach(adapter IN LISTS adapters)
  file(READ "${adapter}" content)
  string(REGEX MATCHALL "extern[ \t\r\n]+\"C\"[ \t\r\n]+[^;{}(]*gneiss_[a-zA-Z0-9_]+[ \t\r\n]*\\(" entries "${content}")
  foreach(entry IN LISTS entries)
    string(REGEX MATCH "gneiss_[a-zA-Z0-9_]+[ \t\r\n]*\\($" symbol "${entry}")
    string(REGEX REPLACE "[ \t\r\n]*\\($" "" symbol "${symbol}")
    if(symbol IN_LIST definitions)
      message(FATAL_ERROR "重复公共 C 定义：${symbol}")
    endif()
    list(APPEND definitions "${symbol}")
  endforeach()
endforeach()
list(SORT definitions)
if(NOT "${definitions}" STREQUAL "${expected}")
  message(FATAL_ERROR "engine/api 的公共定义与稳定性清单不一致")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/check_cpp_types.cmake")
