# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gneiss contributors

cmake_minimum_required(VERSION 3.23)
# 每次重建专用夹具，避免公共头迁移后残留旧文件；删除前确认位于构建目录内。
file(REAL_PATH "${GNEISS_BINARY_DIR}" fixture_root)
set(fixture "${fixture_root}/cpp-inventory-fixture")
file(REAL_PATH "${fixture}" resolved_fixture)
cmake_path(IS_PREFIX fixture_root "${resolved_fixture}" NORMALIZE fixture_in_build)
if(NOT fixture_in_build OR resolved_fixture STREQUAL fixture_root)
  message(FATAL_ERROR "清单夹具路径不在构建目录内：${resolved_fixture}")
endif()
file(REMOVE_RECURSE "${fixture}")
file(MAKE_DIRECTORY "${fixture}/src/engine/api" "${fixture}/abi")
file(MAKE_DIRECTORY "${fixture}/include")
file(COPY "${GNEISS_SOURCE_DIR}/include/gneiss" DESTINATION "${fixture}/include")
configure_file("${GNEISS_SOURCE_DIR}/abi/api-stability.txt" "${fixture}/abi/api-stability.txt" COPYONLY)
configure_file("${GNEISS_SOURCE_DIR}/abi/cpp-api-inventory.json"
  "${fixture}/abi/cpp-api-inventory.json" COPYONLY)
configure_file("${GNEISS_SOURCE_DIR}/abi/cpp-type-inventory.json"
  "${fixture}/abi/cpp-type-inventory.json" COPYONLY)
file(READ "${fixture}/abi/cpp-type-inventory.json" type_inventory)
file(READ "${fixture}/abi/cpp-api-inventory.json" inventory)
string(JSON count LENGTH "${inventory}" functions)
math(EXPR last "${count} - 1")
set(complete "")
set(missing "")
foreach(index RANGE 0 ${last})
  string(JSON symbol GET "${inventory}" functions ${index} symbol)
  set(definition "extern \"C\" void ${symbol}() {}\n")
  string(APPEND complete "${definition}")
  if(index EQUAL 0)
    set(first "${definition}")
  else()
    string(APPEND missing "${definition}")
  endif()
endforeach()
foreach(case IN ITEMS valid missing duplicate extra pending unowned unwrapped untested missing_wrapper missing_type missing_constant unmapped_type extra_type extra_constant)
  set(probe_inventory "${inventory}")
  set(probe_types "${type_inventory}")
  file(WRITE "${fixture}/include/gneiss/inventory_probe.h" "")
  if(case STREQUAL "valid")
    set(content "${complete}")
  elseif(case STREQUAL "missing")
    set(content "${missing}")
  elseif(case STREQUAL "duplicate")
    set(content "${complete}${first}")
  elseif(case STREQUAL "extra")
    set(content "${complete}extern \"C\" void gneiss_unregistered_probe() {}\n")
  else()
    set(content "${complete}")
    if(case STREQUAL "pending")
      string(JSON probe_inventory SET "${inventory}" functions 0 review "\"pending\"")
    elseif(case STREQUAL "unowned")
      string(JSON probe_inventory SET "${inventory}" functions 0 ownership "\"\"")
    elseif(case STREQUAL "unwrapped")
      string(JSON probe_inventory SET "${inventory}" functions 0 cpp_entry "\"\"")
    elseif(case STREQUAL "untested")
      string(JSON probe_inventory SET "${inventory}" functions 0 tests "[]")
    elseif(case STREQUAL "missing_wrapper")
      string(JSON probe_inventory SET "${inventory}" functions 0 cpp_candidate_files
        "[\"include/gneiss/no_such_wrapper.hpp\"]")
    elseif(case STREQUAL "missing_type")
      string(JSON probe_types REMOVE "${type_inventory}" headers 0 types 0)
    elseif(case STREQUAL "missing_constant")
      string(JSON probe_types REMOVE "${type_inventory}" headers 0 constants 0)
    elseif(case STREQUAL "unmapped_type")
      string(JSON probe_types SET "${type_inventory}" headers 0 types 0 cpp_mapping "\"\"")
    elseif(case STREQUAL "extra_type")
      file(WRITE "${fixture}/include/gneiss/inventory_probe.h" "typedef uint64_t gneiss_inventory_probe;\n")
    elseif(case STREQUAL "extra_constant")
      file(WRITE "${fixture}/include/gneiss/inventory_probe.h" "#define GNEISS_INVENTORY_PROBE 1\n")
    endif()
  endif()
  file(WRITE "${fixture}/abi/cpp-type-inventory.json" "${probe_types}")
  file(WRITE "${fixture}/abi/cpp-api-inventory.json" "${probe_inventory}")
  file(WRITE "${fixture}/src/engine/api/probe.cpp" "${content}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DGNEISS_SOURCE_DIR=${fixture}"
    -P "${GNEISS_SOURCE_DIR}/cmake/check_cpp_inventory.cmake"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(case STREQUAL "valid" AND NOT result EQUAL 0)
    message(FATAL_ERROR "清单检查错误拒绝完整边界定义")
  elseif(NOT case STREQUAL "valid" AND result EQUAL 0)
    message(FATAL_ERROR "清单检查未拒绝 ${case} 定义")
  endif()
endforeach()
