# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Gneiss contributors

cmake_minimum_required(VERSION 3.23)
set(fixture "${GNEISS_BINARY_DIR}/cpp-inventory-fixture")
file(MAKE_DIRECTORY "${fixture}/src/api/c" "${fixture}/abi" "${fixture}/docs/records/artifacts")
configure_file("${GNEISS_SOURCE_DIR}/abi/api-stability.txt" "${fixture}/abi/api-stability.txt" COPYONLY)
configure_file("${GNEISS_SOURCE_DIR}/docs/records/artifacts/0.45-api-inventory.json"
  "${fixture}/docs/records/artifacts/0.45-api-inventory.json" COPYONLY)
file(READ "${fixture}/docs/records/artifacts/0.45-api-inventory.json" inventory)
string(JSON count LENGTH "${inventory}" functions)
math(EXPR last "${count} - 1")
set(complete "")
set(missing "")
foreach(index RANGE 0 ${last})
  string(JSON symbol GET "${inventory}" functions ${index} symbol)
  set(definition "extern \"C\" void ${symbol}() {}\n")
  string(APPEND complete "${definition}")
  if(index EQUAL 0)
    set(first "${definition}")
  else()
    string(APPEND missing "${definition}")
  endif()
endforeach()
foreach(case IN ITEMS valid missing duplicate extra)
  if(case STREQUAL "valid")
    set(content "${complete}")
  elseif(case STREQUAL "missing")
    set(content "${missing}")
  elseif(case STREQUAL "duplicate")
    set(content "${complete}${first}")
  else()
    set(content "${complete}extern \"C\" void gneiss_unregistered_probe() {}\n")
  endif()
  file(WRITE "${fixture}/src/api/c/probe.cpp" "${content}")
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DGNEISS_SOURCE_DIR=${fixture}"
    -P "${GNEISS_SOURCE_DIR}/cmake/check_cpp_inventory.cmake"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
  if(case STREQUAL "valid" AND NOT result EQUAL 0)
    message(FATAL_ERROR "清单检查错误拒绝完整边界定义")
  elseif(NOT case STREQUAL "valid" AND result EQUAL 0)
    message(FATAL_ERROR "清单检查未拒绝 ${case} 定义")
  endif()
endforeach()
